### PR TITLE
Contributor Page

### PR DESCRIPTION
**Pull request by urbanengr**
The index, style, and script files form a bare knuckles Contributor page. There's not much styling, but javascript does provide a starting point in adding formatted names.

### CODE REVIEW

**Review by mattkuznicki-ll — COMMENTED** [review]
Hi @urbanengr thanks for this contribution! A couple of questions about this:

1. The files you've added appear to be at the root level of the repository. Is this where we want them to be? I'm wondering if these are intended to be in the project directory for the web application rather than the root of the repository?
2. In the contributors array, it looks like there are a couple people with just first names - is this intended? Also, can I confirm we have their permission to list them?
3. I like that there's the beginnings of common CSS styling included in here. It looks like you've defined CSS for H1 and H3 tags, though in your HTML you use H1 and H2 tags. Is this intentional?

**Comment by urbanengr** [comment]
Hi Matt,
Thanks for taking a look at this.
1.The files were intended to be in the project directory. I'm very new at this so please, let me know how to put them where they belong.
2. I made up the names in the contributor list, except one, Valerie Gilbert - who is me, and you certainly have my permission! I added the names for testing.
4. Ha, no that's not intentional. The HTML and CSS was something I through in to see if the javascript worked. Again, I am a newbie at everything, so I'm open to any wisdom you care to share.

**Comment by mattkuznicki-ll** [comment]
Hi @urbanengr, you can move your files to where you want them to be using the 'git mv' command to move the files to new names and/or locations where you want them to be. If you're using a graphical git client, you can probably move them with that tool. Then, push your changes to your branch and this PR will automatically pick them up.
Often, when a pull request is put up, they'll be some changes requested. Changes to a PR can be made by pushing updates to the source branch. If you look at https://github.com/Lasagna-Love-Portal/project-ricotta/pull/5, for example, you'll see where I added some updates to a PR I made in response to feedback.
Same for changes you may want to make for other items. For these, I'd recommend fixing up your style.css so you define an H2 appearance (as used in your PR) rather than an H3 appearance that's not used. I'd also recommend removing the testing entries from the contributor list. I usually like to have any testing data that I include in a PR in a test, rather than directly in code. It's easy for future contributors and reviewers to misinterpret the meaning of test data left in code. If you want more than one contributor for the list, you can include me and you can reach out to others in this repository who have made or commented on pull requests for permission. But maybe easy enough just to include yourself for the time being.
To make updates, you can push to your branch as described above. Or if it's easier, feel free to close this PR and make a new one with updates and open that when it's ready.

**Review by patimejia — COMMENTED** [review]
> Hi @urbanengr, Very nice work 🚀!

> I wanted to give it a try writing up my first code review if you are okay with it. So I wrote up a generic step-by-step guide targeting anyone interested in following up on your already prepared code. Thanks!

## Code Review for @urbanengr based on https://github.com/Lasagna-Love-Portal/project-ricotta/pull/17

1. Open your terminal and navigate to the root directory of your local `project-ricotta` repository:

    ```bash
    cd path/to/project-ricotta
    ```

2. Create a new branch to work on your changes. Replace `your-username` with your GitHub username:

    ```css
    git checkout -b your-username/update-contributor-page
    ```

3. Navigate to the `public` directory and create a new folder called `contributors`:

    ```bash
    cd packages/web-client/public
    mkdir contributors
    ```

4. Move your existing files (`index.html`, `script.js`, and `style.css`) to the new `contributors` folder using the `git mv` command:

    ```bash
    git mv index.html contributors/
    git mv script.js contributors/
    git mv style.css contributors/
    ```

5. Update the references to the files in your `index.html` file:

    Change this line:

    ```html
    <link href="style.css" rel="stylesheet" />
    ```

    To this:

    ```html
    <link href="contributors/style.css" rel="stylesheet" />
    ```

    And this line:

    ```html
    <script src="script.js"></script>
    ```

    To this:

    ```html
    <script src="contributors/script.js"></script>
    ```

6. Modify your `style.css` file to use `H2` tags instead of `H3` tags for your headings. Remove the testing entries from the contributor list in your `script.js` file as advised by @mattkuznicki-ll (https://github.com/Lasagna-Love-Portal/project-ricotta/pull/17#issuecomment-1496209428 thanks!🎈), because of best-practices. 

7. Stage your changes and commit them:

    ```bash
    git add .
    git commit -m "Move contributor page files to new folder and update file references"
    ```

8. Push your changes to your branch:

    ```bash
    git push -u origin your-username/update-contributor-page
    ```

9. Go to the GitHub website and create a new pull request from your `your-username/update-contributor-page` branch to the `dev` branch.

10. Wait for feedback and address any requested changes by making updates to your branch, committing the changes, and pushing them to the branch.

11. Once your pull request has been approved, it can be merged into the `dev` branch.

> Let me know if you encounter any issues or if I missed anything. 

> Thanks again! Best of luck!

**Pull request closed without merging**
