### PR TITLE
RICOTTA-26: some initial infra thoughts

### PR DESCRIPTION
**Pull request by mkantzer**
This represents a bit of an early attempt / thought for how we could get some infra stood up in a managed way. 

It's fairly opinionated, especially in its usage of Terraform Cloud. This seemed easier and faster than trying to also bootstrap backend components in azure, and it comes built-in with some automation options we may want to make use of. We can stay within the free tier if we keep the tf cloud org to 5 or fewer users. (Note: that number is _not_ the number of repo contributors).

The most important missing piece of the tflcoud system is the ability to set a workspace as VCS controlled, but that should be trivial to add.

The `bootstrap` component basically just creates all followup tfcloud projects/workspaces, as well as providing each with programatic azure authentication. 

The `raw_sandbox` component is basically a minimum-viable SSHable virtual machine. This system has some major issues, most notably storing the SSH private key in state. The next pass at this would probably set a new input for a `public` key, and then just use _that_. 

Also, this solution won't scale for an actual, operable dev environment: updating it is highly manual.

I'm pretty sure I'll also need to open 80/443. 

Nothing has been deployed (or even attempted yet), as I don't have azure credentials to kick off the bootstrapping.

### CODE REVIEW

**Comment by mattkuznicki-ll** [comment]
Hi @mkantzer and thanks for the suggestion and thoughts here. I always respect people bringing an opinion! I'm not well versed with Terraform & invite others who are to contribute to the conversation here. That said, a few items for consideration:
1. It's very likely we're not going to want to host anything directly in a VM in Azure. We're going to be better off with an Azure Web App Service, I believe - lower cost and easier failover, less infrastructure to directly have to maintain, and a smaller potential attack surface to secure. I've hosted web apps in VMs and in App Services & operationally the App Services approach is much easier

2. Getting a deployment pipeline in Azure DevOps to deploy updated Web App Services automatically on updates to branches (whether dev, main or otherwise) is pretty smooth once one gets the hang of it. I get the impression from your PR message that doing so in Terraform is more challenging?

3. Looking over the Terraform script provided, there's some provision of network architecture that looks very similar to what one would do with ARM (Azure Resource Manager) templates via the Azure cloud shell. Not sure what we gain with bringing Terraform in to do this for our Azure environment - then again, I've not worked with Terraform before.

I really appreciate that you're thinking of infrastructure as code from the start! Again, I'd want to hear from others regarding what Terraform brings our use case that Azure DevOps & ARM scripts wouldn't.

**Comment by pid1** [comment]
@mattkuznicki-ll ARM templates are functionally equivalent to Terraform, just a different infrastructure as code tool. Same end goal.

I'm agreed on running the production infrastructure on Azure App Service, I don't see a compelling reason for dedicated hardware.

For dev/staging environments, is there a benefit to hosting them in the cloud versus Dockerizing the existing application? That would seem like the most low barrier to entry and cost effective route.

**Comment by mkantzer** [comment]
I'm 100% in favor of not using a raw VM. This was specifically in response to an ask to quickly get a basic demo/sandbox available, with the idea that we'd build the long-term, containerized solution after. 

My thoughts for that type of environment were to containerize and then use [Azure Container Apps](https://azure.microsoft.com/en-us/products/container-apps), although I'm certainly not an azure expert so I'd defer to those on the best path forward there.

This was my first foray into Azure, so I'm _very_ open to feedback on the network stack. It's almost entirely copy/pasted from the linux VM QuickStart. Again, my target here was turnaround time, with the assumption that this'll be EOL'd quickly. 

RE: terraform: 
- I used it over ARM because it's what I'm familiar with, and wanted to focus on doing the azure part right instead of learning a new language.
- I also haven't used Azure DevOps before, but hooking the terraform cloud workspace up to automatically follow a branch (including pre-planning on a PR) is straightforward. You generally just need to add 2 values to the workspace definition (and the plumbing to get them from the variables file to the resource).
- Terraform doesn't manage the docker build/push process. I'd usually have GitHub Actions build and push `main` and `dev` with the git sha as a tag, and have the terraform update the runtime to use the new tag. 

If this is all more easily done with azure-native tooling, that's fine with me. 

RE: dev/staging:
- I think the goal here was to just get _something_ quick.
- I don't think that we should be going "sandbox per dev" long (or even medium) term. Ideally we get things sufficiently dockerized so that it's reliable for CI or a dev who wants to use it.
- There was a goal to have a demo environment, which is why i figured cloud.

Long term, it probably only makes sense to have cloud hosted:
- production (`main`)
- staging (`dev`?) (to validate the any changes work in the cloud hosting system: docker's great, but there's still app config)

**Comment by mattkuznicki-ll** [comment]
@pid1 I'd like to support pure local development for developers, separate from a staging environment hosted in Azure that will track the 'dev' branch. For this, likely we're looking at one or more Docker containers run locally in a developer's environment. We don't want to bring the existing application that's currently deployed in production into this environment, though. We want to start fresh.
@mkantzer I don't know if any of this is easier in ARM templates vs. Terraform. Talking to some people, though - the IaaC goal is laudable and may be good to visit later on. But to start, any sort of staging environment is an environment we can likely set up by hand to start. That's likely the fastest way to get going. Azure DevOps can be used to push updates to a staging environment hosted in Azure (tracking 'dev') that makes it easy for people to see updates without having to host a development setup themselves.

The desire to get something up sooner rather than later is understood, though we don't necessarily need to automate getting a starting point up. I'd suggest that at least the initial Azure-hosted staging environment may best be hand built so we can get a better handle on what we do want to have.

**Pull request closed without merging**
