### PR TITLE
Attempt to reintegrate PR #22 welcome page

### PR DESCRIPTION
**Pull request by mattkuznicki-ll**
This PR aims to bring back in as much as feasible the changes made in https://github.com/Lasagna-Love-Portal/project-ricotta/pull/22 that added a main welcome page holder for the frontend app.

The reset of the project away from a monorepo and to this project-ricotta repository being the repository for the front-end app changes the structure of the project some. The reset also added Next.js and tailwind as used components, this required some rework of the existing React work to fit into a React + Next.js framework.

I've little experience with React and none with Next.js, so it's quite possible I missed some things.

### CODE REVIEW

**Comment by mattkuznicki-ll** [comment]
@allyson-s-code it'd be great to get your feedback and testing on this! I think I brought over most all of your work, please let me know if there's anything significant I missed or messed up.

**Comment by mattkuznicki-ll** [comment]
Discussion with @allyson-s-code trying to test surfaced some issues with the added Typescript and project layout. Updates made and 4b5de90 should address this.
Note that the Docker build allows the project to run without building the next.js project, while running locally has problems, when there are certain TypeScript issues. There may be something more to look into there.

**Comment by allyson-s-code** [comment]
@mattkuznicki-ll As far as I can tell it seems that everything carried over besides the styling.  There's a lot I'm unsure of having no experience with Next, Typescript, or Tailwind.  Definitely would love some more eyes on it.  
I see some styling issues for sure- it looks like the className attribute can not properly get the styles from the css file because of the hyphens.  Instead of dot notation we can use brackets.  So `className="styles.welcome-screen `can become `className={styles['welcome-screen']}`.  But, I see that Tailwind was added to the project- I'm not familiar with Tailwind- does this mean that maybe we want all inline styles?  Do we want a separate css file module? Also, it seems like the button is not getting the styles from the theme so I am trying to figure out why...

**Comment by mattkuznicki-ll** [comment]
@allyson-s-code I think Tailwind is a common CSS styling library used with Next.js projects & is included in the stub project that comes with making a new Next.js project. I don't know that we're using anything from it presently - but I don't believe we want just inline styles. Better to aim for as much common/global styling as we can to reduce repetition and make maintaining easier, IMO.
Think we can figure out getting the styling fetching in a separate PR from this one? I'd like to unblock others from working on things if possible.

**Comment by allyson-s-code** [comment]
Yes, absolutely!  Sounds good to me.

**Review by emmanolan — APPROVED** [review]

**Pull request merged**
