### PR TITLE
Initial pass at Dockerizing our development setup

### PR DESCRIPTION
**Pull request by pid1**
Any and all feedback welcome and encouraged.

### CODE REVIEW

**Comment by mkantzer** [comment]
I'll take a look a bit later today, but I'm working on something similar-but-beefier, while also fully re-initializing as "just" nextjs without lerna. 

Going to also have some mostly-optimized layer/stage caching so things are _fairly_ quick.

**Comment by pid1** [comment]
Go for it! I was able to use this to perform the frontend reviews, so we are at least up and running.

**Comment by mkantzer** [comment]
https://github.com/Lasagna-Love-Portal/project-ricotta/pull/27

Note that this can't be merged yet. We'd need to backport any frontend work that was done, and I've got some docs to write. 

There's also some _git nonsense_ I need to do. A rebase is probably the extent of it, but rebasing _and_ porting the frontend work is beyond my actual understanding of JS. I can give it a wack later though?

**Comment by pid1** [comment]
@mkantzer That sounds good to me. Let's keep https://github.com/Lasagna-Love-Portal/project-ricotta/pull/27 as a WIP until we can backport the existing frontend work. Let me know if you want to merge this in the meantime.

**Review by emmanolan — APPROVED** [review]

**Pull request merged**
